### ISSUE TITLE
markdown: reports incorrect location when unsupported feature is used

### ISSUE THREAD

**Issue by edwintorok** [darioteixeira/lambdoc#24]
$ cat >x.md <<EOF
aaaa
bbbb

dddd

EOF

lambdoc says: `The document uses an unsupported feature (Html_comment).` and highlights the first line in the source, but the unsupported feature is used on line 4 actually.

**Comment by darioteixeira** [comment]
The resolution is the same as that of issue #25: Since commit f59a2ae, there is now a Lamblite parser that handles both Markdown and Wiki syntaxes, bypassing OMD altogether, and having proper support for location information.
