### ISSUE TITLE
markdown: assertion failed when parsing inline html

### ISSUE THREAD

**Issue by edwintorok** [darioteixeira/lambdoc#25]
```
$ cat >x.md <<EOF
X<sup>2</sup>
EOF
$ lambcmd.native -i x.md -o x.html
Fatal error: exception File "lib/lambdoc_read_markdown_impl/mapper.ml", line 102, characters 12-18: Assertion failed
```

The file `x.md` was obtained by trying to use pandoc to generate a markdown without extensions, so that `omd` [can parse it](https://github.com/ocaml/omd/issues/131):
```
$ cat >y.md <<EOF
X^2^
EOF
$ pandoc -f markdown -t markdown_strict y.md >x.md
```

For now I've added this so that `lambcmd` doesn't crash when trying to parse my files,
but it reports the error at an incorrect location like in [this bug](https://github.com/darioteixeira/lambdoc/issues/24) so I'm not sending a pull request on this yet:

```diff
--- a/src/lib/lambdoc_read_markdown_impl/mapper.ml
+++ b/src/lib/lambdoc_read_markdown_impl/mapper.ml
@@ -99,7 +99,7 @@ let ast_of_omd frag =
                                | Some (href, _title) -> Inline (dummy, Ast.Link ( href, Some ([(dummy, Ast.Plain txt)])))
                                | None -> Inline (dummy, Ast.Plain fallback#to_string)
                        end
-               | _                             -> assert false
+               | e -> raise (Unsupported_feature (Omd.to_markdown [e]))
```

**Comment by darioteixeira** [comment]
Since commit f59a2aebcbd3990c41b501210052e20e5725f186, there is now a Lamblite parser that handles both Markdown and Wiki syntaxes, bypassing OMD altogether.  This issue is therefore moot.
