### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by Drup** [darioteixeira/lambdoc#7]
I investigated the extension mechanism and I find it insufficient for my needs.

Imagine I would like to do a plugin where you include dot source and it replaces it by an svg. For that I need 
 - To define a new type of *block*. inline commands like extern, link and image are not appropriate
 - To have knowledge of the output format, to be able to output the raw svg.

In this example, I probably could get away by using a picture pointing to a dot file, but I have other examples where It's not possible to go through an external file.

**Comment by darioteixeira** [comment]
I think this ticket may be closed for now.  The extension mechanism is fairly flexible and powerful already, and I reckon it won't require any further changes before 1.0 (famous last words...).
Okay with you, @Drup and @edwintorok ?

**Comment by edwintorok** [comment]
OK to close, I think the extension mechanism is general enough now.
Might have to write a few convenience functions on top of foldmapper to make it easier to write certain kinds of extensions, but those don't necessarily have to come with lambdoc, they can be part of the extension itself. The only way to know for sure is to actually try and write some extensions.
Do you have  a timeframe in mind for 1.0?

**Comment by darioteixeira** [comment]
@edwintorok: I definitely want to refactor the Lambtex and Lambwiki parsers before 1.0.  I'm just waiting for the next Menhir version to come out, which according to François Pottier should happen soon (the next Menhir version has features which should make on-the-fly lexer switching much easier and cleaner).  I would also like to finalise the Lambtex language itself (fix issues #29 and #33).  There are other smaller issues, but none of those are really show-stoppers.

**Comment by darioteixeira** [comment]
@Drup and @edwintorok: I'm closing this issue, as I'm reasonably happy with the current extension mechanism.  Feel free to reopen the issue if new ideas pop up!
